# GENERATED by coding-agents/refresh-gateway-models.py — do not edit by hand.
#
# What the Juspay LiteLLM gateway (https://grid.ai.juspay.net) served when this
# was last refreshed, as the key in $JUSPAY_API_KEY sees it. Availability is per key,
# so a teammate whose key covers different models refreshes this file and gets
# their own view; `git log` on this file is its clock.
#
# Each entry:
#   context   - context window in tokens, from the gateway
#   output    - max output tokens, from the gateway
#   reasoning - reasons by default (omitted when the gateway does not say)
#   vision    - accepts image input (omitted when the gateway does not say)

{
  "claude-opus-4-5" = { context = 1000000; output = 128000; reasoning = true; vision = true; };
  "claude-opus-4-6" = { context = 1000000; output = 128000; reasoning = true; vision = true; };
  "claude-sonnet-4-5" = { context = 200000; output = 64000; reasoning = true; vision = true; };
  "claude-sonnet-4-6" = { context = 200000; output = 64000; reasoning = true; vision = true; };
  "gemini-3.1-pro" = { context = 1048576; output = 65536; reasoning = true; vision = true; };
  "glm-flash-experimental" = { context = 128000; output = 128000; reasoning = false; vision = false; };
  "glm-latest" = { context = 400000; output = 32000; reasoning = true; vision = false; };
  "kimi-k3" = { context = 256000; output = 32000; };
  "kimi-latest" = { context = 256000; output = 32000; };
  "open-fast" = { context = 256000; output = 32000; reasoning = true; vision = false; };
  "open-large" = { context = 400000; output = 32000; reasoning = true; vision = false; };
}
