#!/usr/bin/env python3
"""Regenerate coding-agents/gateway-models.nix from the Juspay LiteLLM gateway.

The gateway is the only authority on which models it serves, their context
windows and their capabilities. This snapshot exists for the one agent that
cannot ask it at runtime: opencode's provider catalog is models.dev plus models
you declare, and a private gateway is in neither. (OMP discovers the same data
itself — see coding-agents/omp/juspay-oneclick.nix.)

    just refresh-gateway-models

Sources, merged per model id:

  GET /v1/models                  key-scoped ids with context/output limits
  LiteLLM's metadata routes       mode + capability flags. They are
                                  complementary rather than ranked — the
                                  gateway's own view and the operator's
                                  per-deployment `model_info` each answer
                                  partially — and OMP's discovery probes the
                                  same set, so both agents end up agreeing.
                                  Which ones a key may read depends on the
                                  deployment's `allowed_routes`; if none of
                                  them answers, this refuses to write rather
                                  than commit a snapshot that silently lost
                                  every capability flag and can no longer tell
                                  a chat model from an embedding one.

Merge rules, so the output is deterministic:

  * a model is dropped when a row reports a non-chat `mode`, or when no row
    states its limits at all;
  * limits take the widest value across rows;
  * a flag is true if any row says true, false if none do and at least one says
    false, and omitted when no row says anything.
"""

import argparse
import difflib
import json
import os
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

# LiteLLM's task-specific modes; anything here is not a chat model, so it does
# not belong in an agent's model picker.
NON_CHAT_MODES = {
    "audio_speech",
    "audio_transcription",
    "batch",
    "embedding",
    "guardrail",
    "image_edit",
    "image_generation",
    "moderation",
    "ocr",
    "rerank",
    "search",
    "vector_store",
    "video_generation",
}

# LiteLLM's metadata routes, newest spelling first.
RICH_ENDPOINTS = ("/model_group/info", "/v2/model/info", "/model/info", "/v1/model/info")

# A model, as the snapshot records it. Limits always exist; a flag is None when
# no row stated it, and the consumer decides what silence means.
@dataclass(frozen=True)
class Model:
    context: int
    output: int
    reasoning: bool | None = None
    vision: bool | None = None


HEADER = """# GENERATED by coding-agents/refresh-gateway-models.py — do not edit by hand.
#
# What the Juspay LiteLLM gateway ({gateway}) served when this
# was last refreshed, as the key in ${key_env} sees it. Availability is per key,
# so a teammate whose key covers different models refreshes this file and gets
# their own view; `git log` on this file is its clock.
#
# Each entry:
#   context   - context window in tokens, from the gateway
#   output    - max output tokens, from the gateway
#   reasoning - reasons by default (omitted when the gateway does not say)
#   vision    - accepts image input (omitted when the gateway does not say)
"""


def fetch(url, key):
    request = urllib.request.Request(url, headers={"Authorization": f"Bearer {key}"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def fold(rows, limits, flags):
    """Fold one endpoint's rows into the per-id limits and flags."""
    for row in rows:
        model_id = row.get("id") or row.get("model_name")
        if not model_id:
            continue
        info = row.get("model_info") or {}

        slots = limits.setdefault(model_id, {"context": None, "output": None})
        for field, key in (("context", "max_input_tokens"), ("output", "max_output_tokens")):
            value = info.get(key) or row.get(key)
            if isinstance(value, int) and (slots[field] is None or value > slots[field]):
                slots[field] = value

        stated = flags.setdefault(model_id, {"mode": set(), "reasoning": set(), "vision": set()})
        if info.get("mode"):
            stated["mode"].add(info["mode"])
        for flag, key in (("reasoning", "supports_reasoning"), ("vision", "supports_vision")):
            if isinstance(info.get(key), bool):
                stated[flag].add(info[key])


def tri_state(values):
    """True if anything says true, False if only false is known, None if silent."""
    if True in values:
        return True
    if False in values:
        return False
    return None


def render(gateway, key_env, models):
    lines = [HEADER.format(gateway=gateway, key_env=key_env), "{"]
    for model_id in sorted(models):
        model = models[model_id]
        fields = [f"context = {model.context};", f"output = {model.output};"]
        if model.reasoning is not None:
            fields.append(f"reasoning = {str(model.reasoning).lower()};")
        if model.vision is not None:
            fields.append(f"vision = {str(model.vision).lower()};")
        lines.append(f'  "{model_id}" = {{ {" ".join(fields)} }};')
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--gateway", required=True, help="gateway base URL, e.g. https://grid.ai.juspay.net")
    parser.add_argument("--key-env", required=True, help="environment variable holding the gateway API key")
    args = parser.parse_args()

    key = os.environ.get(args.key_env)
    if not key:
        sys.exit(f"{args.key_env} is not set — it must hold a gateway API key.")

    base = args.gateway.rstrip("/")
    limits, flags, answered = {}, {}, []
    fold(fetch(f"{base}/v1/models", key).get("data", []), limits, flags)
    for endpoint in RICH_ENDPOINTS:
        try:
            fold(fetch(f"{base}{endpoint}", key).get("data", []), limits, flags)
            answered.append(endpoint)
        except urllib.error.HTTPError as error:
            print(f"note: {endpoint} -> {error.code}", file=sys.stderr)
    if not answered:
        sys.exit(
            f"none of {', '.join(RICH_ENDPOINTS)} answered with this key, so the snapshot\n"
            "would lose every capability flag and could no longer tell a chat model from an\n"
            "embedding one. LiteLLM exposes these routes per key via `allowed_routes`;\n"
            "refresh with a key that may read one of them."
        )
    print(f"sources: /v1/models, {' '.join(answered)}")

    models, dropped = {}, []
    for model_id, slots in limits.items():
        stated = flags.get(model_id, {})
        if NON_CHAT_MODES & stated.get("mode", set()):
            continue
        if slots["context"] is None or slots["output"] is None:
            dropped.append(model_id)
            continue
        models[model_id] = Model(
            context=slots["context"],
            output=slots["output"],
            reasoning=tri_state(stated.get("reasoning", set())),
            vision=tri_state(stated.get("vision", set())),
        )

    for model_id in sorted(dropped):
        print(f"warning: dropped {model_id}: no row states its context/output limits", file=sys.stderr)

    output = Path(__file__).resolve().parent / "gateway-models.nix"
    rendered = render(args.gateway, args.key_env, models)

    previous = output.read_text() if output.exists() else ""
    if previous == rendered:
        print(f"{output.name}: up to date ({len(models)} models)")
        return 0

    output.write_text(rendered)
    print(f"{output.name}: written ({len(models)} models)")
    sys.stdout.writelines(
        line + "\n" for line in difflib.unified_diff(
            previous.splitlines(), rendered.splitlines(), "before", "after", n=1, lineterm=""
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
